services:
  backend:
    build: ./
    restart: always
    ports:
      - 8080:8001
    volumes:
      - ./:/app/
    networks:
      - redis-net
  redis:
    image: "redis:alpine"
    networks:
      - redis-net
networks:
  redis-net:
    driver: bridge